[config]
schemaVersion = "0.0.1"

[package]
namespace = "DeathMonger"
name = "ForsakenShrines"
versionNumber = "0.8.1"
description = "Build shrines to the Forsaken bosses. Each shrine remotely channels its boss's guardian power once you mount the boss's trophy on it, to switch forsaken powers without having to return to the sacrificial stones at the world center."
websiteUrl = "https://thunderstore.io/c/valheim/p/DeathMonger/ForsakenShrines/"
containsNsfwContent = false

[package.dependencies]
"denikson-BepInExPack_Valheim" = "5.4.2202"
"ValheimModding-Jotunn" = "2.23.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release/net48/ForsakenShrines.dll"
target = "BepInEx/plugins/"

[publish]
repository = "https://thunderstore.io"
communities = ["valheim"]

[publish.categories]
valheim = ["mods", "building", "server-side", "crafting", "utility", "ai-generated"]
