<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>StationExtensionGuard</RootNamespace>
    <AssemblyName>StationExtensionGuard</AssemblyName>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <NoWarn>$(NoWarn);MSB3277</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HarmonyX" Version="2.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="assembly_valheim_publicized">
      <HintPath>..\Libs\assembly_valheim_publicized.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\Libs\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\Libs\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine_publicized">
      <HintPath>..\Libs\UnityEngine_publicized.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
